### PR TITLE
Solve Errors & Update Dependencies 2018

### PR DESCRIPTION
**Pull request by DesWurstes**
~~Make sure to put https://codeload.github.com/gruntjs/grunt-contrib-livereload/zip/master into node modules after installing other dependencies and unzipping it.~~ See the bottom.

### CODE REVIEW

**Comment by RafaAguilar** [comment]
I tried to run `npm install` and it didn't let me, this was the output for the error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for grunt-contrib-livereload@1.0.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'Strut'
npm ERR! notarget
```

**Comment by DesWurstes** [comment]
Fixed

> Make sure to put https://codeload.github.com/gruntjs/grunt-contrib-livereload/zip/master into node modules after installing other dependencies and unzipping it.

^^^still needed

**Comment by sirm1972** [comment]
hi,
I have not been able to solve NPM install problems!
I have followed these instructions without success  
this error continues to appear

```
# npm install
Strut@0.4.0 /home/Projects/Strut
├─┬ UNMET PEER DEPENDENCY grunt@1.0.3
│ ├─┬ findup-sync@0.3.0
│ │ └─┬ glob@5.0.15
│ │   └── inflight@1.0.6 
│ └─┬ glob@7.0.6
│   └── inflight@1.0.6 
└── grunt-mocha@1.1.0 

npm WARN grunt-contrib-livereload@0.1.2 requires a peer of grunt@~0.4.0 but none was installed.
npm WARN Strut@0.4.0 No repository field.
npm WARN Strut@0.4.0 No license field.
```

```
# grunt server
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'server-static'
Warning: Task "server" not found. Use --force to continue.

Aborted due to warnings.
```
The steps I have followed are:

1.- Install the latest Grunt: npm install -g grunt-cli
2.- Clone Strut: git clone git://github.com/tantaman/Strut.git
3.- cd Strut
4.-	Update dependencies via NCU
5.-	fix files: 

Gruntfile.js
app/scripts/libs/Handlebars.js
app/scripts/libs/require.js
app/preview_export/scripts/impress.js
update:    package.json     **(without  "grunt-contrib-livereload": "1.0.1")**

6.- npm install
7.- grunt server


I would appreciate if someone could tell me what I'm doing wrong.

pd: Operating System: Ubuntu 18.04 LTS

**Comment by DesWurstes** [comment]
Install from git clone git://github.com/DesWurstes/Strut.git

**Comment by sirm1972** [comment]
thanks, but I got this error:

```
$ sudo grunt server
Running "server" task
Warning: Task "livereload-start" not found. Use --force to continue.

Aborted due to warnings.
```

my solution was to comment on this line in the file Gruntfile.js
**//       'livereload-start',**

```
grunt.task.run([
            'clean:server',
            'handlebars',
     //     'livereload-start',
            'connect:livereload',
            'watch'
```
it works!!

**Comment by tantaman** [comment]
sooo this actually works then?  I'll give it a test tonight and ... hopefully re-deploy the strut.io site.

**Comment by DesWurstes** [comment]
@tantaman Could you please try again? I've solved the livereload issue, extra steps other than `npm i` and `grunt server` aren't needed anymore.

**Comment by tantaman** [comment]
thanks so much for this.  Its just what I needed to resurrect the project and come back to it.

**Pull request merged**
